# Generated by Django 4.2.20 on 2025-03-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('psu', 'Блок питания'), ('storage', 'Накопитель'), ('cooler', 'Система охлаждения')], max_length=20)),
                ('required_attribute', models.CharField(help_text="Например: 'Сокет', 'Тип памяти'", max_length=255)),
                ('allowed_values', models.TextField(help_text='Разделенные запятой допустимые значения')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooler', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Системы охлаждения'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('cpu', models.ForeignKey(limit_choices_to={'category__name': 'Процессоры'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('gpu', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Видеокарты'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('motherboard', models.ForeignKey(limit_choices_to={'category__name': 'Материнские платы'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('psu', models.ForeignKey(limit_choices_to={'category__name': 'Блоки питания'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('ram', models.ForeignKey(limit_choices_to={'category__name': 'Оперативная память'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('storage', models.ForeignKey(limit_choices_to={'category__name': 'Накопители'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
